In [ ]:
import numpy as np
#Array attributes
np.random.seed(0) #seed for repoducibility.

In [ ]:
x1=np.random.randint(10, size=6) #one-dimensional array
x2=np.random.randint(10, size=(3, 4)) #Two-dimensional array
x3=np.random.randint(10, size=(3, 4, 5)) #Three-dimensional array


In [ ]:
print("x3 ndim: ", x3.ndim) #The number of dimension

x3 ndim:  3


In [ ]:
print("x3 shape:", x3.shape) #the size of each dimension

x3 shape: (3, 4, 5)


In [ ]:
print("x3 size:", x3.size) #The total size of the array

x3 size: 60


In [ ]:
print("dtype", x3.dtype) #Data of the array

dtype int64


In [ ]:
print("itemsize", x3.itemsize, "Bytes")

itemsize 8 Bytes


In [ ]:
print("Nbsize", x3.nbytes, "bytes")

Nbsize 480 bytes


Array indexing: Accesing Single Elements

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4]

7

To index from the end of array, you can use negative indices:

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

7

In a multi-dimensional array, items can be acessed using a comma-separated tuple of indices.

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0,0]

3

In [ ]:
x2[0,1]

5

Values can also be modified using any of the above index notation:

In [ ]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Numpy arrays have a fixed type. if you attempt to insert a floating-point value to an integer array, the value will be silenty truncated. Example:

In [ ]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

#One dimension Subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5] #First five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] #Elements after index 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7] #Middle sub-array

array([4, 5, 6])

In [ ]:
x[::2] #Every other element

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2] #Every other element start at index 1

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1] #All elements, reversed 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2] #reversed every other from the index 5

array([5, 3, 1])

multi-dimensional slices work in the same way

acessing array rows and columns

In [ ]:
print(x2[:,0]) #first column of x2

[12  7  1]


In [ ]:
print(x2[0]) #first row of 2 #or x2[0, :]

[12  5  2  4]


#Creating copy of arrays

In [ ]:
x2_sub_copy = x2[:2, :2].copy() #If we now modify this subarray , the original array is not touched
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [ ]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#Reshaping of arrays

In [ ]:
#If you want to put the numbers 1 throuh 9 in a 3x3 grid.

In [ ]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


For this work, the size of the initial array must match the size of the reshaped array.

In [ ]:
#Conversion of a one-dimensional array into a two-dimensional row or column matrix
#Reshape method or newaxis

In [ ]:
x = np.array([1, 2, 3])
# Row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
#Row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [ ]:
#Column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
#Column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#Array concatenation and Splitting

Concatenation: np.concatenate, np.vstack, and np.hstack. np.concatenate

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) #You can also concatenate more than two arrays at once

array([1, 2, 3, 3, 2, 1])

In [ ]:
#it can also be used for two-dimensional arrays:
grid = np.array([[1, 2, 3], [4, 5, 6,]])

In [ ]:
#concatenate along the first axis 
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

for working with arrays of mixed dimensions, it be clearer to use the np.vstack(vertical stack) and nphstack(horizontal stack).

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7 ],
                 [6, 5, 4]])
#vertical stacks
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
#Horizontal stacks
y = np.array([[99],
              [99]] )
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Splitting of arrays
impletemented by the functions np.split, np.hsplit and vsplit

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
