<a href="https://colab.research.google.com/github/SabrinaRoses/Data_Science/blob/main/Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introducing Ufuncs

In [14]:
#Imagine we have an array of values and we'd like to compute the reciprocal of each.
#A straighforward approach might look like this.

import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [16]:
big_array = np.random.randint(1, 100, size=100000)
%time compute_reciprocals(big_array)

CPU times: user 216 ms, sys: 271 µs, total: 216 ms
Wall time: 217 ms


array([0.01030928, 0.5       , 0.02380952, ..., 0.01219512, 0.01369863,
       0.0125    ])

In [18]:
#Operate between two arrays
np.arange(5) / np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [19]:
x = np.arange(9).reshape((3,3)) #multi-dimensional
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented using Python loops, especially as the arrays grow in size. Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

#Exploring Numpy's Ufuncs
Ufuncs exist in two flavors: unary ufuncs , which operate on a single input, 
and binary ufuncs, which operate on two inputs.

#Array arithmetic

In [22]:
x = np.arange(4)
print("x = ", x)
print("x + 5 =", x + 5)
print("x - 5 =", x-5)
print("x * 5 = ", x * 5)
print("x / 5 =", x /5 )
print("x // 5 = ", x //2) #Floor division

x =  [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 5 =  [ 0  5 10 15]
x / 5 = [0.  0.2 0.4 0.6]
x // 5 =  [0 0 1 1]


There is also a unary ufunc for negation, and a ** operator for expotentiation,
and a % operator for moduls:

In [23]:
print("x -", -x)
print("x**2 = ", x**2)
print("x % 2 = ", x % 2)

x - [ 0 -1 -2 -3]
x**2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In addition, these can strung together however you wish, and the standard order of operations is repected.

Also the operador + is a wrapper for the add function.

In [24]:
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

Operator	Equivalent ufunc	Description
+	np.add	Addition (e.g., 1 + 1 = 2)
-	np.subtract	Subtraction (e.g., 3 - 2 = 1)
-	np.negative	Unary negation (e.g., -2)
*	np.multiply	Multiplication (e.g., 2 * 3 = 6)
/	np.divide	Division (e.g., 3 / 2 = 1.5)
//	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
**	np.power	Exponentiation (e.g., 2 ** 3 = 8)
%	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

#Absolute Value
just as NumPy understands Python's Built-in arithmetic operator, it also undertands Python's built-in absolute value function.
The corresponding NumPy ufunc is np.absolute, whichis also available under the alis np.abs:

In [27]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [28]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [29]:
np.abs(x)

array([2, 1, 0, 1, 2])

This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [31]:
x = np.array([3-4j, 4 -3j, 2 + 0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

#Trigonometric Functions

In [32]:
theta = np.linspace(0, np.pi, 3)
#now we can use some trigonometric functions on theses values

In [33]:
print("Theta =", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta = ", np.tan(theta))

Theta = [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The valus are computade within machine precision, whichis why values that should be zero do not always hit exactly zero. Inverse trigonemetric functions are also available: 

In [37]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


#Exponents and logarithms

In [38]:
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available. The basic np.log gives the natural logarithm; if you prefer to compute the base 2 logarithm or the base 10 logarithm, there are available as well.

In [42]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x)", np.log(x))
print("log2(x)", np.log2(x))
print("log10(x) = ", np.log10(x))

x = [1, 2, 4, 10]
ln(x) [0.         0.69314718 1.38629436 2.30258509]
log2(x) [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [45]:
#when x is very small these functions give more precise values than if the raw
# np.log or np.exp were to be used:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 = ", np.expm1(x))
print("log(1 + x)) = ", np.log1p(x))

exp(x) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1 + x)) =  [0.         0.0009995  0.00995033 0.09531018]
